from dataclasses import dataclass

from sqlalchemy import create_engine, Column, Integer, String, SmallInteger, Text, DECIMAL, Date, DateTime, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

Base = declarative_base()


@dataclass
class MacVod(Base):
    __tablename__ = 'mac_vod'

    vod_id = Column(Integer, primary_key=True, autoincrement=True)
    type_id = Column(SmallInteger, nullable=False, default=0)
    type_id_1 = Column(SmallInteger, nullable=False, default=0)
    group_id = Column(SmallInteger, nullable=False, default=0)
    vod_name = Column(String(255), nullable=False, default='')
    vod_sub = Column(String(255), nullable=False, default='')
    vod_en = Column(String(255), nullable=False, default='')
    vod_status = Column(SmallInteger, nullable=False, default=0)
    vod_letter = Column(String(1), nullable=False, default='')
    vod_color = Column(String(6), nullable=False, default='')
    vod_tag = Column(String(100), nullable=False, default='')
    vod_class = Column(String(255), nullable=False, default='')
    vod_pic = Column(String(1024), nullable=False, default='')
    vod_pic_thumb = Column(String(1024), nullable=False, default='')
    vod_pic_slide = Column(String(1024), nullable=False, default='')
    vod_pic_screenshot = Column(Text)
    vod_actor = Column(String(255), nullable=False, default='')
    vod_director = Column(String(255), nullable=False, default='')
    vod_writer = Column(String(100), nullable=False, default='')
    vod_behind = Column(String(100), nullable=False, default='')
    vod_blurb = Column(String(255), nullable=False, default='')
    vod_remarks = Column(String(100), nullable=False, default='')
    vod_pubdate = Column(String(100), nullable=False, default='')
    vod_total = Column(Integer, nullable=False, default=0)
    vod_serial = Column(String(20), nullable=False, default='0')
    vod_tv = Column(String(30), nullable=False, default='')
    vod_weekday = Column(String(30), nullable=False, default='')
    vod_area = Column(String(20), nullable=False, default='')
    vod_lang = Column(String(10), nullable=False, default='')
    vod_year = Column(String(10), nullable=False, default='')
    vod_version = Column(String(30), nullable=False, default='')
    vod_state = Column(String(30), nullable=False, default='')
    vod_author = Column(String(60), nullable=False, default='')
    vod_jumpurl = Column(String(150), nullable=False, default='')
    vod_tpl = Column(String(30), nullable=False, default='')
    vod_tpl_play = Column(String(30), nullable=False, default='')
    vod_tpl_down = Column(String(30), nullable=False, default='')
    vod_isend = Column(SmallInteger, nullable=False, default=0)
    vod_lock = Column(SmallInteger, nullable=False, default=0)
    vod_level = Column(SmallInteger, nullable=False, default=0)
    vod_copyright = Column(SmallInteger, nullable=False, default=0)
    vod_points = Column(SmallInteger, nullable=False, default=0)
    vod_points_play = Column(SmallInteger, nullable=False, default=0)
    vod_points_down = Column(SmallInteger, nullable=False, default=0)
    vod_hits = Column(Integer, nullable=False, default=0)
    vod_hits_day = Column(Integer, nullable=False, default=0)
    vod_hits_week = Column(Integer, nullable=False, default=0)
    vod_hits_month = Column(Integer, nullable=False, default=0)
    vod_duration = Column(String(10), nullable=False, default='')
    vod_up = Column(Integer, nullable=False, default=0)
    vod_down = Column(Integer, nullable=False, default=0)
    vod_score = Column(DECIMAL(3, 1), nullable=False, default=0.0)
    vod_score_all = Column(Integer, nullable=False, default=0)
    vod_score_num = Column(Integer, nullable=False, default=0)
    vod_time = Column(Integer, nullable=False, default=0)
    vod_time_add = Column(Integer, nullable=False, default=0)
    vod_time_hits = Column(Integer, nullable=False, default=0)
    vod_time_make = Column(Integer, nullable=False, default=0)
    vod_trysee = Column(SmallInteger, nullable=False, default=0)
    vod_douban_id = Column(Integer, nullable=False, default=0)
    vod_douban_score = Column(DECIMAL(3, 1), nullable=False, default=0.0)
    vod_reurl = Column(String(255), nullable=False, default='')
    vod_rel_vod = Column(String(255), nullable=False, default='')
    vod_rel_art = Column(String(255), nullable=False, default='')
    vod_pwd = Column(String(10), nullable=False, default='')
    vod_pwd_url = Column(String(255), nullable=False, default='')
    vod_pwd_play = Column(String(10), nullable=False, default='')
    vod_pwd_play_url = Column(String(255), nullable=False, default='')
    vod_pwd_down = Column(String(10), nullable=False, default='')
    vod_pwd_down_url = Column(String(255), nullable=False, default='')
    vod_content = Column(Text, nullable=False)
    vod_play_from = Column(String(255), nullable=False, default='')
    vod_play_server = Column(String(255), nullable=False, default='')
    vod_play_note = Column(String(255), nullable=False, default='')
    vod_play_url = Column(Text, nullable=False)
    vod_down_from = Column(String(255), nullable=False, default='')
    vod_down_server = Column(String(255), nullable=False, default='')
    vod_down_note = Column(String(255), nullable=False, default='')
    vod_down_url = Column(Text, nullable=False)
    vod_plot = Column(SmallInteger, nullable=False, default=0)
    vod_plot_name = Column(Text, nullable=False)
    vod_plot_detail = Column(Text, nullable=False)
